# Generated by Django 2.0.5 on 2018-05-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TC_app', '0003_auto_20180529_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
