# Generated by Django 2.0.5 on 2018-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC_app', '0004_auto_20180529_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_data',
            field=models.CharField(default='{}', max_length=900),
        ),
    ]
